# Generated by Django 4.1.3 on 2023-01-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_bookdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdb',
            name='Priceperday',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookdb',
            name='Synopsis',
            field=models.TextField(default=100, max_length=200),
            preserve_default=False,
        ),
    ]
