# Generated by Django 4.1.3 on 2023-01-10 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_bookdb_priceperday_bookdb_synopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdb',
            name='Priceperday',
            field=models.IntegerField(null=True),
        ),
    ]
