# Generated by Django 4.1.3 on 2023-02-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_bookdb_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdb',
            name='color',
        ),
        migrations.AlterField(
            model_name='bookdb',
            name='Description',
            field=models.CharField(choices=[('ROMANCE', 'Romance'), ('ADVENTURE', 'Adventure'), ('HORROR', 'Horror'), ('SCIENCE FICTION', 'Science Fiction')], default='ADVENTURE', max_length=15),
        ),
    ]
